/* eslint-disable */
/**
 * AUTO-GENERATED by `npm run api:generate` from the M10 FastAPI OpenAPI
 * schema (openapi/openapi.json). Do not hand-edit -- edit the FastAPI
 * schema and regenerate instead (M11A task §4).
 */

export interface paths {
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Cases */
        get: operations["get_review_cases_api_v1_review_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-cases/{review_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Case Detail */
        get: operations["get_review_case_detail_api_v1_review_cases__review_case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-cases/{review_case_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review Command */
        post: operations["submit_review_command_api_v1_review_cases__review_case_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiCorrectionRequest */
        ApiCorrectionRequest: {
            /** Corrected Value */
            corrected_value: string;
            /** Evidence Reference Ids */
            evidence_reference_ids: string[];
            field_name: components["schemas"]["InvoiceFieldName"];
            /** Line Number */
            line_number?: number | null;
            /** Previous Value */
            previous_value?: string | null;
            /** Reason */
            reason: string;
        };
        /** ApiEnvelope */
        ApiEnvelope: {
            /** Data */
            data?: unknown | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiReviewCommandRequest */
        ApiReviewCommandRequest: {
            action: components["schemas"]["ReviewAction"];
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Corrections
             * @default []
             */
            corrections: components["schemas"]["ApiCorrectionRequest"][];
            disposition?: components["schemas"]["HumanReviewDisposition"] | null;
            /** Idempotency Key */
            idempotency_key: string;
            /** Notes */
            notes?: string | null;
            /** Observed Review Revision */
            observed_review_revision: number;
            /** Observed Workflow Revision */
            observed_workflow_revision: number;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HumanReviewDisposition
         * @enum {string}
         */
        HumanReviewDisposition: "APPROVED" | "REJECTED" | "HOLD" | "NEEDS_INFORMATION" | "CORRECTED";
        /**
         * InvoiceFieldName
         * @enum {string}
         */
        InvoiceFieldName: "SUPPLIER_NAME" | "SUPPLIER_ADDRESS" | "CUSTOMER_NAME" | "CUSTOMER_ADDRESS" | "INVOICE_NUMBER" | "INVOICE_DATE" | "DUE_DATE" | "PURCHASE_ORDER_NUMBER" | "CURRENCY" | "SUBTOTAL" | "TAX_AMOUNT" | "DISCOUNT_AMOUNT" | "SHIPPING_AMOUNT" | "TOTAL_AMOUNT" | "PAYMENT_TERMS" | "LINE_DESCRIPTION" | "LINE_QUANTITY" | "LINE_UNIT_PRICE" | "LINE_AMOUNT";
        /**
         * ReviewAction
         * @enum {string}
         */
        ReviewAction: "CLAIM" | "RELEASE" | "ACCEPT" | "CORRECT" | "CONFIRM_SUPPLIER" | "CONFIRM_PURCHASE_ORDER" | "REQUEST_INFORMATION" | "ESCALATE" | "REJECT" | "RESUME_WORKFLOW";
        /**
         * ReviewPriority
         * @enum {string}
         */
        ReviewPriority: "LOW" | "NORMAL" | "HIGH" | "CRITICAL";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_cases_api_v1_review_cases_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number | null;
                /** @description ReviewCaseStatus value */
                status?: string | null;
                assigned_to?: string | null;
                priority?: components["schemas"]["ReviewPriority"] | null;
                batch_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_case_detail_api_v1_review_cases__review_case_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
            };
            path: {
                /** @description Human-review case identifier */
                review_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_command_api_v1_review_cases__review_case_id__commands_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
            };
            path: {
                /** @description Human-review case identifier */
                review_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiReviewCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope"];
                };
            };
        };
    };
}
