/* eslint-disable */
/**
 * AUTO-GENERATED by `npm run api:generate` from the M10 FastAPI OpenAPI
 * schema (openapi/openapi.json). Do not hand-edit -- edit the FastAPI
 * schema and regenerate instead (M11A task §4).
 */

export interface paths {
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_operations_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Detail */
        get: operations["get_job_detail_api_v1_operations_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Invoice */
        post: operations["submit_invoice_api_v1_operations_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Cases */
        get: operations["get_review_cases_api_v1_review_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-cases/{review_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Case Detail */
        get: operations["get_review_case_detail_api_v1_review_cases__review_case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-cases/{review_case_id}/command-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Command Capabilities
         * @description Advisory, read-only projection of what this actor may attempt on this
         *     case right now (M11C task §6). The command executors still re-validate
         *     everything transactionally; nothing here authorises anything.
         */
        get: operations["get_review_command_capabilities_api_v1_review_cases__review_case_id__command_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-cases/{review_case_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review Command */
        post: operations["submit_review_command_api_v1_review_cases__review_case_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiCorrectionRequest */
        ApiCorrectionRequest: {
            /** Corrected Value */
            corrected_value: string;
            /** Evidence Reference Ids */
            evidence_reference_ids: string[];
            field_name: components["schemas"]["InvoiceFieldName"];
            /** Line Number */
            line_number?: number | null;
            /** Previous Value */
            previous_value?: string | null;
            /** Reason */
            reason: string;
        };
        /** ApiEnvelope[CommandCapabilitiesResponse] */
        ApiEnvelope_CommandCapabilitiesResponse_: {
            data?: components["schemas"]["CommandCapabilitiesResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[DashboardResponse] */
        ApiEnvelope_DashboardResponse_: {
            data?: components["schemas"]["DashboardResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[HealthResponse] */
        ApiEnvelope_HealthResponse_: {
            data?: components["schemas"]["HealthResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[InvoiceDetailResponse] */
        ApiEnvelope_InvoiceDetailResponse_: {
            data?: components["schemas"]["InvoiceDetailResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[JobDetailResponse] */
        ApiEnvelope_JobDetailResponse_: {
            data?: components["schemas"]["JobDetailResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[JobListResponse] */
        ApiEnvelope_JobListResponse_: {
            data?: components["schemas"]["JobListResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[ReviewQueuePageResponse] */
        ApiEnvelope_ReviewQueuePageResponse_: {
            data?: components["schemas"]["ReviewQueuePageResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[SessionResponse] */
        ApiEnvelope_SessionResponse_: {
            data?: components["schemas"]["SessionResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[SubmissionResponse] */
        ApiEnvelope_SubmissionResponse_: {
            data?: components["schemas"]["SubmissionResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /** ApiEnvelope[Union[ValidationOnlyCommandResponse, CommandResultResponse, WorkflowResumeResponse]] */
        ApiEnvelope_Union_ValidationOnlyCommandResponse__CommandResultResponse__WorkflowResumeResponse__: {
            /** Data */
            data?: components["schemas"]["ValidationOnlyCommandResponse"] | components["schemas"]["CommandResultResponse"] | components["schemas"]["WorkflowResumeResponse"] | null;
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Status */
            status: string;
        };
        /**
         * ApiErrorEnvelope
         * @description Shape of every controlled error body (`ap_agent.api.errors`).
         */
        ApiErrorEnvelope: {
            /** Errors */
            errors: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ApiReviewCommandRequest */
        ApiReviewCommandRequest: {
            action: components["schemas"]["ReviewAction"];
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Corrections
             * @default []
             */
            corrections: components["schemas"]["ApiCorrectionRequest"][];
            disposition?: components["schemas"]["HumanReviewDisposition"] | null;
            /** Idempotency Key */
            idempotency_key: string;
            /** Notes */
            notes?: string | null;
            /** Observed Review Revision */
            observed_review_revision: number;
            /** Observed Workflow Revision */
            observed_workflow_revision: number;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
        };
        /** AvailableAction */
        AvailableAction: {
            action: components["schemas"]["ReviewAction"];
            disposition: components["schemas"]["HumanReviewDisposition"] | null;
            /** Requires Corrections */
            requires_corrections: boolean;
            /** Requires Notes */
            requires_notes: boolean;
            /** Requires Reason Codes */
            requires_reason_codes: boolean;
        };
        /** CommandCapabilitiesResponse */
        CommandCapabilitiesResponse: {
            /** Actor Role */
            actor_role: string;
            /**
             * Assignment
             * @enum {string}
             */
            assignment: "UNASSIGNED" | "ASSIGNED_TO_ACTOR" | "ASSIGNED_TO_OTHER";
            /** Available Actions */
            available_actions: components["schemas"]["AvailableAction"][];
            case_status: components["schemas"]["ReviewCaseStatus"];
            /**
             * Command Mode
             * @enum {string}
             */
            command_mode: "COMMIT" | "VALIDATION_ONLY";
            correction_policy: components["schemas"]["CorrectionPolicyResponse"];
            /**
             * Payment Execution
             * @constant
             */
            payment_execution: "PROHIBITED";
            /** Permitted Actions */
            permitted_actions: components["schemas"]["ReviewAction"][];
            resume: components["schemas"]["ResumeCapabilityResponse"];
            /** Review Revision */
            review_revision: number;
            /** Unsupported Actions */
            unsupported_actions: components["schemas"]["ReviewAction"][];
            /** Workflow Revision */
            workflow_revision: number;
        };
        /** CommandResultResponse */
        CommandResultResponse: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Decision Id */
            decision_id: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Message */
            message: string;
            resulting_case_status: components["schemas"]["ReviewCaseStatus"] | null;
            /** Resulting Revision */
            resulting_revision: number | null;
            /**
             * Review Case Id
             * Format: uuid
             */
            review_case_id: string;
            status: components["schemas"]["InterfaceCommandStatus"];
            /** Workflow Resumed */
            workflow_resumed: boolean;
        };
        /** CorrectableHeaderField */
        CorrectableHeaderField: {
            /** Current Value */
            current_value: string | null;
            field_name: components["schemas"]["InvoiceFieldName"];
        };
        /** CorrectableLineValue */
        CorrectableLineValue: {
            /** Current Value */
            current_value: string | null;
            field_name: components["schemas"]["InvoiceFieldName"];
            /** Line Number */
            line_number: number;
        };
        /** CorrectionPolicyResponse */
        CorrectionPolicyResponse: {
            /** Evidence Reference Ids */
            evidence_reference_ids: string[];
            /** Header Fields */
            header_fields: components["schemas"]["CorrectableHeaderField"][];
            /** Line Fields */
            line_fields: components["schemas"]["InvoiceFieldName"][];
            /** Line Numbers */
            line_numbers: number[];
            /** Line Values */
            line_values: components["schemas"]["CorrectableLineValue"][];
            /** Require Evidence */
            require_evidence: boolean;
            /** Require Reason */
            require_reason: boolean;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Completed Invoices */
            completed_invoices: number;
            /** Failed Invoices */
            failed_invoices: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Open Review Cases */
            open_review_cases: number;
            /** Processing Invoices */
            processing_invoices: number;
            /** Review Reason Counts */
            review_reason_counts: components["schemas"]["ReviewReasonCount"][];
            /** Review Required Invoices */
            review_required_invoices: number;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Total Invoices */
            total_invoices: number;
            /** Unassigned Review Cases */
            unassigned_review_cases: number;
        };
        /** FinancialCheckResponse */
        FinancialCheckResponse: {
            /** Check Id */
            check_id: string;
            /** Check Type */
            check_type: string;
            /** Evidence Reference Ids */
            evidence_reference_ids: string[];
            /** Expected Value */
            expected_value: string | null;
            /** Message */
            message: string;
            /** Observed Value */
            observed_value: string | null;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /**
             * Command Mode
             * @enum {string}
             */
            command_mode: "COMMIT" | "VALIDATION_ONLY";
            /**
             * Operations Mode
             * @default DISABLED
             * @enum {string}
             */
            operations_mode: "ENABLED" | "DISABLED";
            /**
             * Payment Execution
             * @constant
             */
            payment_execution: "PROHIBITED";
            /** Service */
            service: string;
        };
        /**
         * HumanReviewDisposition
         * @enum {string}
         */
        HumanReviewDisposition: "APPROVED" | "REJECTED" | "HOLD" | "NEEDS_INFORMATION" | "CORRECTED";
        /**
         * InterfaceCommandStatus
         * @enum {string}
         */
        InterfaceCommandStatus: "ACCEPTED" | "IDEMPOTENT" | "REJECTED" | "CONFLICT" | "FAILED";
        /** InterfaceFieldValueResponse */
        InterfaceFieldValueResponse: {
            /** Confidence */
            confidence: number | null;
            /** Evidence Reference Ids */
            evidence_reference_ids: string[];
            field_name: components["schemas"]["InvoiceFieldName"];
            /** Normalized Value */
            normalized_value: string | null;
            /** Raw Value */
            raw_value: string | null;
            /** Review Required */
            review_required: boolean;
            value_type: components["schemas"]["NormalizedValueType"];
        };
        /** InvoiceDetailResponse */
        InvoiceDetailResponse: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            case_status: components["schemas"]["ReviewCaseStatus"];
            current_stage: components["schemas"]["OrchestrationStage"];
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Fields */
            fields: components["schemas"]["InterfaceFieldValueResponse"][];
            /** Financial Checks */
            financial_checks: components["schemas"]["FinancialCheckResponse"][];
            /** Line Matches */
            line_matches: components["schemas"]["LineMatchResponse"][];
            /** Original Document Uri */
            original_document_uri: string | null;
            /**
             * Review Case Id
             * Format: uuid
             */
            review_case_id: string;
            /** Review Decisions */
            review_decisions: components["schemas"]["ReviewDecisionResponse"][];
            /** Review Reasons */
            review_reasons: string[];
            /** Review Required */
            review_required: boolean;
            /** Review Revision */
            review_revision: number;
            /** Source Document Sha256 */
            source_document_sha256: string;
            /** Source Name */
            source_name: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Timeline */
            timeline: components["schemas"]["TimelineEventResponse"][];
            /**
             * Workflow Id
             * Format: uuid
             */
            workflow_id: string;
            workflow_status: components["schemas"]["InvoiceWorkflowStatus"];
        };
        /**
         * InvoiceFieldName
         * @enum {string}
         */
        InvoiceFieldName: "SUPPLIER_NAME" | "SUPPLIER_ADDRESS" | "CUSTOMER_NAME" | "CUSTOMER_ADDRESS" | "INVOICE_NUMBER" | "INVOICE_DATE" | "DUE_DATE" | "PURCHASE_ORDER_NUMBER" | "CURRENCY" | "SUBTOTAL" | "TAX_AMOUNT" | "DISCOUNT_AMOUNT" | "SHIPPING_AMOUNT" | "TOTAL_AMOUNT" | "PAYMENT_TERMS" | "LINE_DESCRIPTION" | "LINE_QUANTITY" | "LINE_UNIT_PRICE" | "LINE_AMOUNT";
        /**
         * InvoiceWorkflowStatus
         * @enum {string}
         */
        InvoiceWorkflowStatus: "PENDING" | "IN_PROGRESS" | "SUCCEEDED" | "REVIEW_REQUIRED" | "FAILED" | "SKIPPED";
        /** JobDetailResponse */
        JobDetailResponse: {
            /** Events */
            events: components["schemas"]["JobEventResponse"][];
            job: components["schemas"]["JobResponse"];
        };
        /** JobEventResponse */
        JobEventResponse: {
            /** Attempt Number */
            attempt_number: number;
            /** Error Code */
            error_code: string | null;
            /** Event Type */
            event_type: string;
            /** Message */
            message: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Sequence Number */
            sequence_number: number;
            /** Stage */
            stage: string | null;
            /** Status */
            status: string;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Items */
            items: components["schemas"]["JobResponse"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** JobResponse */
        JobResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Byte Size */
            byte_size: number | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Stage */
            current_stage: string | null;
            /** Error Code */
            error_code: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Job Type
             * @enum {string}
             */
            job_type: "PROCESS_DOCUMENT" | "RESUME_WORKFLOW";
            /** Media Type */
            media_type: string | null;
            /** Resumed Review Case Id */
            resumed_review_case_id: string | null;
            /** Review Case Id */
            review_case_id: string | null;
            /** Source Name */
            source_name: string;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "REVIEW_REQUIRED" | "FAILED";
            summary: components["schemas"]["JobSummaryResponse"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workflow Id */
            workflow_id: string | null;
        };
        /** JobStageSummary */
        JobStageSummary: {
            /** Attempt */
            attempt: number;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
        };
        /** JobSummaryResponse */
        JobSummaryResponse: {
            /**
             * Corrected Fields
             * @default []
             */
            corrected_fields: string[];
            /** Currency */
            currency?: string | null;
            /** Decision Id */
            decision_id?: string | null;
            /** Derived Version */
            derived_version?: string | null;
            /**
             * Executed Stages
             * @default []
             */
            executed_stages: string[];
            /** Financial Validation Status */
            financial_validation_status?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Memory Version Id */
            memory_version_id?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Purchase Order Status */
            purchase_order_status?: string | null;
            /** Restart Stage */
            restart_stage?: string | null;
            /** Resume Plan Id */
            resume_plan_id?: string | null;
            /**
             * Review Reasons
             * @default []
             */
            review_reasons: string[];
            /** Review Required */
            review_required?: boolean | null;
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["JobStageSummary"][];
            /** Supplier Name */
            supplier_name?: string | null;
            /** Supplier Status */
            supplier_status?: string | null;
            /** Total Amount */
            total_amount?: string | null;
            /** Workflow Status */
            workflow_status?: string | null;
        };
        /** LineMatchResponse */
        LineMatchResponse: {
            /** Description Status */
            description_status: string;
            /** Invoice Line Number */
            invoice_line_number: number | null;
            /** Line Match Id */
            line_match_id: string;
            /** Line Total Status */
            line_total_status: string;
            /** Purchase Order Line Number */
            purchase_order_line_number: number | null;
            /** Quantity Status */
            quantity_status: string;
            /** Review Reasons */
            review_reasons: string[];
            /** Review Required */
            review_required: boolean;
            /** Unit Price Status */
            unit_price_status: string;
        };
        /**
         * NormalizedValueType
         * @enum {string}
         */
        NormalizedValueType: "TEXT" | "DATE" | "DECIMAL" | "CURRENCY_CODE";
        /**
         * OrchestrationStage
         * @enum {string}
         */
        OrchestrationStage: "INGESTION" | "PREPROCESSING" | "OCR" | "NORMALIZATION" | "FINANCIAL_VALIDATION" | "REFERENCE_MATCHING" | "MEMORY_PERSISTENCE" | "HUMAN_REVIEW" | "COMPLETED";
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Count */
            total_count: number;
            /** Total Pages */
            total_pages: number;
        };
        /** ResumeCapabilityResponse */
        ResumeCapabilityResponse: {
            /** Already Requested */
            already_requested: boolean;
            /** Decision Id */
            decision_id: string | null;
            disposition: components["schemas"]["HumanReviewDisposition"] | null;
            /** Eligible */
            eligible: boolean;
            /** Ineligible Reason */
            ineligible_reason: string | null;
        };
        /**
         * ReviewAction
         * @enum {string}
         */
        ReviewAction: "CLAIM" | "RELEASE" | "ACCEPT" | "CORRECT" | "CONFIRM_SUPPLIER" | "CONFIRM_PURCHASE_ORDER" | "REQUEST_INFORMATION" | "ESCALATE" | "REJECT" | "RESUME_WORKFLOW";
        /**
         * ReviewCaseStatus
         * @enum {string}
         */
        ReviewCaseStatus: "OPEN" | "IN_REVIEW" | "AWAITING_INFORMATION" | "ESCALATED" | "RESOLVED" | "REJECTED";
        /** ReviewDecisionResponse */
        ReviewDecisionResponse: {
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            disposition: components["schemas"]["HumanReviewDisposition"];
            /** Notes */
            notes: string | null;
            /** Reason Codes */
            reason_codes: string[];
            /** Reviewer Id */
            reviewer_id: string;
        };
        /**
         * ReviewPriority
         * @enum {string}
         */
        ReviewPriority: "LOW" | "NORMAL" | "HIGH" | "CRITICAL";
        /** ReviewQueueItem */
        ReviewQueueItem: {
            /** Assigned Reviewer Id */
            assigned_reviewer_id: string | null;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            case_status: components["schemas"]["ReviewCaseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string | null;
            current_stage: components["schemas"]["OrchestrationStage"];
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Financial Validation Status */
            financial_validation_status: string | null;
            /** Invoice Number */
            invoice_number: string | null;
            priority: components["schemas"]["ReviewPriority"];
            /** Purchase Order Status */
            purchase_order_status: string | null;
            /**
             * Review Case Id
             * Format: uuid
             */
            review_case_id: string;
            /** Review Reasons */
            review_reasons: string[];
            /** Review Revision */
            review_revision: number;
            /** Source Name */
            source_name: string;
            /** Supplier Name */
            supplier_name: string | null;
            /** Supplier Status */
            supplier_status: string | null;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Total Amount */
            total_amount: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Workflow Id
             * Format: uuid
             */
            workflow_id: string;
            workflow_status: components["schemas"]["InvoiceWorkflowStatus"];
        };
        /** ReviewQueuePageResponse */
        ReviewQueuePageResponse: {
            /** Items */
            items: components["schemas"]["ReviewQueueItem"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** ReviewReasonCount */
        ReviewReasonCount: {
            /** Count */
            count: number;
            /** Reason */
            reason: string;
        };
        /**
         * SessionResponse
         * @description M11E: who the authenticated caller is, as the database mapping (not
         *     the identity provider or the browser) defines it.
         */
        SessionResponse: {
            /**
             * Auth Mode
             * @enum {string}
             */
            auth_mode: "prototype_headers" | "clerk_jwt";
            /**
             * Role
             * @enum {string}
             */
            role: "TENANT_ADMIN" | "AP_OPERATOR" | "AP_REVIEWER" | "READ_ONLY_AUDITOR";
            /** Tenant Display Name */
            tenant_display_name?: string | null;
        };
        /** SubmissionResponse */
        SubmissionResponse: {
            /** Idempotent Replay */
            idempotent_replay: boolean;
            job: components["schemas"]["JobResponse"];
        };
        /** TimelineEventResponse */
        TimelineEventResponse: {
            /** Actor Id */
            actor_id: string | null;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Message */
            message: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Stage */
            stage: string | null;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationOnlyCommandResponse
         * @description M11C task §5: the exact JSON the validation-only branch of
         *     `submit_review_command` has always returned (an inline dict literal
         *     until now, hence `data?: unknown` in the generated client).
         */
        ValidationOnlyCommandResponse: {
            action: components["schemas"]["ReviewAction"];
            /** Command Fingerprint */
            command_fingerprint: string;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Database Mutation
             * @constant
             */
            database_mutation: false;
            /**
             * Execution Mode
             * @constant
             */
            execution_mode: "VALIDATION_ONLY";
            /**
             * Review Case Id
             * Format: uuid
             */
            review_case_id: string;
        };
        /** WorkflowResumeResponse */
        WorkflowResumeResponse: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Decision Id */
            decision_id: string | null;
            /** Derived Version */
            derived_version?: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Message */
            message: string;
            restart_stage?: components["schemas"]["OrchestrationStage"] | null;
            resulting_case_status: components["schemas"]["ReviewCaseStatus"] | null;
            /** Resulting Revision */
            resulting_revision: number | null;
            /** Resume Plan Id */
            resume_plan_id?: string | null;
            /**
             * Review Case Id
             * Format: uuid
             */
            review_case_id: string;
            status: components["schemas"]["InterfaceCommandStatus"];
            /** Workflow Resumed */
            workflow_resumed: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_DashboardResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_operations_jobs_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                job_type?: string | null;
                review_case_id?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_JobListResponse_"];
                };
            };
            /** @description Missing or invalid authentication. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Forbidden role, or operations are disabled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unknown job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Idempotency key reused with different content. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Request or file too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unsupported or inconsistent file type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid upload, filename, field or idempotency key. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Redacted internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Database unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    get_job_detail_api_v1_operations_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path: {
                /** @description Job identifier */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_JobDetailResponse_"];
                };
            };
            /** @description Missing or invalid authentication. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Forbidden role, or operations are disabled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unknown job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Idempotency key reused with different content. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Request or file too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unsupported or inconsistent file type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid upload, filename, field or idempotency key. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Redacted internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Database unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    submit_invoice_api_v1_operations_submissions_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        /** @description One supported invoice file (PDF, PNG or JPEG). No other form field is accepted. */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SubmissionResponse_"];
                };
            };
            /** @description Missing or invalid authentication. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Forbidden role, or operations are disabled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unknown job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Idempotency key reused with different content. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Request or file too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unsupported or inconsistent file type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid upload, filename, field or idempotency key. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Redacted internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Database unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    get_review_cases_api_v1_review_cases_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number | null;
                /** @description ReviewCaseStatus value */
                status?: string | null;
                assigned_to?: string | null;
                priority?: components["schemas"]["ReviewPriority"] | null;
                batch_id?: string | null;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_ReviewQueuePageResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_case_detail_api_v1_review_cases__review_case_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path: {
                /** @description Human-review case identifier */
                review_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_InvoiceDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_command_capabilities_api_v1_review_cases__review_case_id__command_capabilities_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path: {
                /** @description Human-review case identifier */
                review_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CommandCapabilitiesResponse_"];
                };
            };
            /** @description Missing or invalid authentication. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Forbidden role or cross-tenant action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unknown review case. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Stale revision, ownership conflict or idempotency-content conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid, unsupported or prohibited command. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Redacted internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Database unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    submit_review_command_api_v1_review_cases__review_case_id__commands_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path: {
                /** @description Human-review case identifier */
                review_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiReviewCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_Union_ValidationOnlyCommandResponse__CommandResultResponse__WorkflowResumeResponse__"];
                };
            };
            /** @description Missing or invalid authentication. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Forbidden role or cross-tenant action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Unknown review case. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Stale revision, ownership conflict or idempotency-content conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid, unsupported or prohibited command. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Redacted internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Database unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    get_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-Actor-ID"?: string | null;
                "X-Actor-Role"?: string | null;
                "X-Authenticated-At"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SessionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_HealthResponse_"];
                };
            };
        };
    };
}
